### ISSUE TITLE
Writeup for Cow Pie is wrong

### ISSUE THREAD

**Issue by MrHobbits** [W3rni0/NahamCon_CTF_2020#3]
Doing strings on the file does not reveal the flag.

File appears to be a qcow2 image file, which once converted to .raw (qemu-img -O raw manure manure.raw)
if you do a fls -o 1 manure.raw will reveal there used to be a file titled "flag.txt" which was deleted.
Using icat -o 1 manure.raw 64 reveals a long string of white space (0x20) (64 = inode of the flag.txt)

**Comment by W3rni0** [comment]
The writeup is not actually wrong but the solution is unintended and was fixed in a later version, I think that the version I used and uploaded to the repo is also the older one.
when I'll have time I'll add the intended solution as well

**Comment by MrHobbits** [comment]
Thanks, I look forward to reading it! If possible, can you download the latest 'manure' file instead of the one that has the flag visible with strings? The newest one has 38 0x20 (spaces) where the flag used to be.
